require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/corps", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Corp. As you add validations to Corp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Corp.create! valid_attributes
      get corps_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      corp = Corp.create! valid_attributes
      get corp_url(corp)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_corp_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      corp = Corp.create! valid_attributes
      get edit_corp_url(corp)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Corp" do
        expect {
          post corps_url, params: { corp: valid_attributes }
        }.to change(Corp, :count).by(1)
      end

      it "redirects to the created corp" do
        post corps_url, params: { corp: valid_attributes }
        expect(response).to redirect_to(corp_url(Corp.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Corp" do
        expect {
          post corps_url, params: { corp: invalid_attributes }
        }.to change(Corp, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post corps_url, params: { corp: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested corp" do
        corp = Corp.create! valid_attributes
        patch corp_url(corp), params: { corp: new_attributes }
        corp.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the corp" do
        corp = Corp.create! valid_attributes
        patch corp_url(corp), params: { corp: new_attributes }
        corp.reload
        expect(response).to redirect_to(corp_url(corp))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        corp = Corp.create! valid_attributes
        patch corp_url(corp), params: { corp: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested corp" do
      corp = Corp.create! valid_attributes
      expect {
        delete corp_url(corp)
      }.to change(Corp, :count).by(-1)
    end

    it "redirects to the corps list" do
      corp = Corp.create! valid_attributes
      delete corp_url(corp)
      expect(response).to redirect_to(corps_url)
    end
  end
end
