require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dataloggers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Datalogger. As you add validations to Datalogger, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Datalogger.create! valid_attributes
      get dataloggers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      datalogger = Datalogger.create! valid_attributes
      get datalogger_url(datalogger)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_datalogger_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      datalogger = Datalogger.create! valid_attributes
      get edit_datalogger_url(datalogger)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Datalogger" do
        expect {
          post dataloggers_url, params: { datalogger: valid_attributes }
        }.to change(Datalogger, :count).by(1)
      end

      it "redirects to the created datalogger" do
        post dataloggers_url, params: { datalogger: valid_attributes }
        expect(response).to redirect_to(datalogger_url(Datalogger.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Datalogger" do
        expect {
          post dataloggers_url, params: { datalogger: invalid_attributes }
        }.to change(Datalogger, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post dataloggers_url, params: { datalogger: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested datalogger" do
        datalogger = Datalogger.create! valid_attributes
        patch datalogger_url(datalogger), params: { datalogger: new_attributes }
        datalogger.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the datalogger" do
        datalogger = Datalogger.create! valid_attributes
        patch datalogger_url(datalogger), params: { datalogger: new_attributes }
        datalogger.reload
        expect(response).to redirect_to(datalogger_url(datalogger))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        datalogger = Datalogger.create! valid_attributes
        patch datalogger_url(datalogger), params: { datalogger: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested datalogger" do
      datalogger = Datalogger.create! valid_attributes
      expect {
        delete datalogger_url(datalogger)
      }.to change(Datalogger, :count).by(-1)
    end

    it "redirects to the dataloggers list" do
      datalogger = Datalogger.create! valid_attributes
      delete datalogger_url(datalogger)
      expect(response).to redirect_to(dataloggers_url)
    end
  end
end
