require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/laptops", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Laptop. As you add validations to Laptop, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Laptop.create! valid_attributes
      get laptops_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      laptop = Laptop.create! valid_attributes
      get laptop_url(laptop)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_laptop_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      laptop = Laptop.create! valid_attributes
      get edit_laptop_url(laptop)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Laptop" do
        expect {
          post laptops_url, params: { laptop: valid_attributes }
        }.to change(Laptop, :count).by(1)
      end

      it "redirects to the created laptop" do
        post laptops_url, params: { laptop: valid_attributes }
        expect(response).to redirect_to(laptop_url(Laptop.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Laptop" do
        expect {
          post laptops_url, params: { laptop: invalid_attributes }
        }.to change(Laptop, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post laptops_url, params: { laptop: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested laptop" do
        laptop = Laptop.create! valid_attributes
        patch laptop_url(laptop), params: { laptop: new_attributes }
        laptop.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the laptop" do
        laptop = Laptop.create! valid_attributes
        patch laptop_url(laptop), params: { laptop: new_attributes }
        laptop.reload
        expect(response).to redirect_to(laptop_url(laptop))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        laptop = Laptop.create! valid_attributes
        patch laptop_url(laptop), params: { laptop: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested laptop" do
      laptop = Laptop.create! valid_attributes
      expect {
        delete laptop_url(laptop)
      }.to change(Laptop, :count).by(-1)
    end

    it "redirects to the laptops list" do
      laptop = Laptop.create! valid_attributes
      delete laptop_url(laptop)
      expect(response).to redirect_to(laptops_url)
    end
  end
end
